# Form implementation generated from reading ui file 'resources/ui/local_program.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_DialogLocalProgram(object):
    def setupUi(self, DialogLocalProgram):
        DialogLocalProgram.setObjectName("DialogLocalProgram")
        DialogLocalProgram.resize(326, 180)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogLocalProgram)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=DialogLocalProgram)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(parent=DialogLocalProgram)
        self.lineEdit.setMaxLength(16)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.labelOverwrite = QtWidgets.QLabel(parent=DialogLocalProgram)
        self.labelOverwrite.setStyleSheet("QLabel{color: red}")
        self.labelOverwrite.setObjectName("labelOverwrite")
        self.verticalLayout.addWidget(self.labelOverwrite)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DialogLocalProgram)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogLocalProgram)
        self.buttonBox.accepted.connect(DialogLocalProgram.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogLocalProgram.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogLocalProgram)

    def retranslateUi(self, DialogLocalProgram):
        _translate = QtCore.QCoreApplication.translate
        DialogLocalProgram.setWindowTitle(_translate("DialogLocalProgram", "Local program name"))
        self.label.setText(_translate("DialogLocalProgram", "<html><head/><body><p>Type here the name of the program.<br>It will also change the program name in the device.</p></body></html>"))
        self.labelOverwrite.setText(_translate("DialogLocalProgram", "<html><head/><body><p>A local program with the same name already exists.<br>It will be overwrited !</p></body></html>"))
