# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(506, 703)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    background-color:#20808080;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 1.5ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center; /* position at the top center */\n"
"    padding: 0 3px;\n"
"    border:2px solid gray;\n"
"    border-radius:5px;\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.progressBarGain = ParamProgressBar(self.groupBox_3)
        self.progressBarGain.setProperty("value", 24)
        self.progressBarGain.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBarGain.setObjectName("progressBarGain")
        self.gridLayout.addWidget(self.progressBarGain, 1, 1, 1, 5)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 12, 0, 1, 1)
        self.progressBarBass = ParamProgressBar(self.groupBox_3)
        self.progressBarBass.setProperty("value", 24)
        self.progressBarBass.setObjectName("progressBarBass")
        self.gridLayout.addWidget(self.progressBarBass, 6, 1, 1, 5)
        self.labelPresenceTone = QtWidgets.QLabel(self.groupBox_3)
        self.labelPresenceTone.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPresenceTone.setObjectName("labelPresenceTone")
        self.gridLayout.addWidget(self.labelPresenceTone, 8, 0, 1, 1)
        self.progressBarResonance = ParamProgressBar(self.groupBox_3)
        self.progressBarResonance.setProperty("value", 24)
        self.progressBarResonance.setObjectName("progressBarResonance")
        self.gridLayout.addWidget(self.progressBarResonance, 9, 1, 1, 5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxLowCut = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxLowCut.setObjectName("checkBoxLowCut")
        self.horizontalLayout.addWidget(self.checkBoxLowCut)
        self.checkBoxMidBoost = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxMidBoost.setObjectName("checkBoxMidBoost")
        self.horizontalLayout.addWidget(self.checkBoxMidBoost)
        self.checkBoxBrightCap = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxBrightCap.setObjectName("checkBoxBrightCap")
        self.horizontalLayout.addWidget(self.checkBoxBrightCap)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 6)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.progressBarTreble = ParamProgressBar(self.groupBox_3)
        self.progressBarTreble.setStyleSheet("\n"
"QProgressBar::chunck {background-color: #888888;}")
        self.progressBarTreble.setProperty("value", 24)
        self.progressBarTreble.setObjectName("progressBarTreble")
        self.gridLayout.addWidget(self.progressBarTreble, 4, 1, 1, 5)
        self.progressBarMiddle = ParamProgressBar(self.groupBox_3)
        self.progressBarMiddle.setProperty("value", 24)
        self.progressBarMiddle.setObjectName("progressBarMiddle")
        self.gridLayout.addWidget(self.progressBarMiddle, 5, 1, 1, 5)
        self.progressBarVolume = ParamProgressBar(self.groupBox_3)
        self.progressBarVolume.setProperty("value", 24)
        self.progressBarVolume.setObjectName("progressBarVolume")
        self.gridLayout.addWidget(self.progressBarVolume, 12, 1, 1, 5)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.progressBarTone = ParamProgressBar(self.groupBox_3)
        self.progressBarTone.setProperty("value", 24)
        self.progressBarTone.setObjectName("progressBarTone")
        self.gridLayout.addWidget(self.progressBarTone, 8, 1, 1, 5)
        self.comboBoxAmpModel = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBoxAmpModel.setObjectName("comboBoxAmpModel")
        self.gridLayout.addWidget(self.comboBoxAmpModel, 0, 0, 1, 6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBoxClassAAB = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxClassAAB.setObjectName("checkBoxClassAAB")
        self.horizontalLayout_2.addWidget(self.checkBoxClassAAB)
        self.checkBoxBiasShift = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxBiasShift.setObjectName("checkBoxBiasShift")
        self.horizontalLayout_2.addWidget(self.checkBoxBiasShift)
        self.gridLayout.addLayout(self.horizontalLayout_2, 13, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color:#20808080;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 1.5ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center; /* position at the top center */\n"
"    padding: 0 3px;\n"
"    border:2px solid gray;\n"
"    border-radius:5px;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.progressBarNoiseGate = ParamProgressBar(self.groupBox)
        self.progressBarNoiseGate.setProperty("value", 24)
        self.progressBarNoiseGate.setObjectName("progressBarNoiseGate")
        self.horizontalLayout_4.addWidget(self.progressBarNoiseGate)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.groupBoxReverb = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxReverb.setStyleSheet("QGroupBox {\n"
"    background-color:#20808080;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 1.5ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center; /* position at the top center */\n"
"    padding: 0 3px;\n"
"    border:2px solid gray;\n"
"    border-radius:5px;\n"
"}")
        self.groupBoxReverb.setCheckable(True)
        self.groupBoxReverb.setObjectName("groupBoxReverb")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBoxReverb)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.progressBarReverbLowDamp = ParamProgressBar(self.groupBoxReverb)
        self.progressBarReverbLowDamp.setProperty("value", 24)
        self.progressBarReverbLowDamp.setObjectName("progressBarReverbLowDamp")
        self.gridLayout_5.addWidget(self.progressBarReverbLowDamp, 6, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBoxReverb)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 4, 0, 1, 1)
        self.progressBarReverbPreDelay = ParamProgressBar(self.groupBoxReverb)
        self.progressBarReverbPreDelay.setProperty("value", 24)
        self.progressBarReverbPreDelay.setObjectName("progressBarReverbPreDelay")
        self.gridLayout_5.addWidget(self.progressBarReverbPreDelay, 5, 1, 1, 1)
        self.progressBarReverbHighDump = ParamProgressBar(self.groupBoxReverb)
        self.progressBarReverbHighDump.setProperty("value", 24)
        self.progressBarReverbHighDump.setObjectName("progressBarReverbHighDump")
        self.gridLayout_5.addWidget(self.progressBarReverbHighDump, 8, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBoxReverb)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 5, 0, 1, 1)
        self.comboBoxReverb = QtWidgets.QComboBox(self.groupBoxReverb)
        self.comboBoxReverb.setObjectName("comboBoxReverb")
        self.gridLayout_5.addWidget(self.comboBoxReverb, 1, 0, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.groupBoxReverb)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 3, 0, 1, 1)
        self.progressBarReverbMix = ParamProgressBar(self.groupBoxReverb)
        self.progressBarReverbMix.setProperty("value", 24)
        self.progressBarReverbMix.setObjectName("progressBarReverbMix")
        self.gridLayout_5.addWidget(self.progressBarReverbMix, 3, 1, 1, 1)
        self.progressBarReverbTime = ParamProgressBar(self.groupBoxReverb)
        self.progressBarReverbTime.setProperty("value", 24)
        self.progressBarReverbTime.setObjectName("progressBarReverbTime")
        self.gridLayout_5.addWidget(self.progressBarReverbTime, 4, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBoxReverb)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 6, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBoxReverb)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 8, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem3, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBoxReverb)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBoxPedal1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxPedal1.setStyleSheet("QGroupBox {\n"
"    background-color:#20808080;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 1.5ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center; /* position at the top center */\n"
"    padding: 0 3px;\n"
"    border:2px solid gray;\n"
"    border-radius:5px;\n"
"}")
        self.groupBoxPedal1.setCheckable(True)
        self.groupBoxPedal1.setObjectName("groupBoxPedal1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxPedal1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.progressBarPedal1Param1 = ParamProgressBar(self.groupBoxPedal1)
        self.progressBarPedal1Param1.setProperty("value", 24)
        self.progressBarPedal1Param1.setObjectName("progressBarPedal1Param1")
        self.gridLayout_2.addWidget(self.progressBarPedal1Param1, 3, 2, 1, 1)
        self.labelPedal1Param0 = QtWidgets.QLabel(self.groupBoxPedal1)
        self.labelPedal1Param0.setObjectName("labelPedal1Param0")
        self.gridLayout_2.addWidget(self.labelPedal1Param0, 2, 0, 1, 1)
        self.progressBarPedal1Param5 = ParamProgressBar(self.groupBoxPedal1)
        self.progressBarPedal1Param5.setProperty("value", 24)
        self.progressBarPedal1Param5.setObjectName("progressBarPedal1Param5")
        self.gridLayout_2.addWidget(self.progressBarPedal1Param5, 7, 2, 1, 1)
        self.progressBarPedal1Param4 = ParamProgressBar(self.groupBoxPedal1)
        self.progressBarPedal1Param4.setProperty("value", 24)
        self.progressBarPedal1Param4.setObjectName("progressBarPedal1Param4")
        self.gridLayout_2.addWidget(self.progressBarPedal1Param4, 6, 2, 1, 1)
        self.labelPedal1Param3 = QtWidgets.QLabel(self.groupBoxPedal1)
        self.labelPedal1Param3.setObjectName("labelPedal1Param3")
        self.gridLayout_2.addWidget(self.labelPedal1Param3, 5, 0, 1, 1)
        self.comboBoxPedal1 = QtWidgets.QComboBox(self.groupBoxPedal1)
        self.comboBoxPedal1.setObjectName("comboBoxPedal1")
        self.gridLayout_2.addWidget(self.comboBoxPedal1, 1, 0, 1, 3)
        self.progressBarPedal1Param3 = ParamProgressBar(self.groupBoxPedal1)
        self.progressBarPedal1Param3.setProperty("value", 24)
        self.progressBarPedal1Param3.setObjectName("progressBarPedal1Param3")
        self.gridLayout_2.addWidget(self.progressBarPedal1Param3, 5, 2, 1, 1)
        self.labelPedal1Param4 = QtWidgets.QLabel(self.groupBoxPedal1)
        self.labelPedal1Param4.setObjectName("labelPedal1Param4")
        self.gridLayout_2.addWidget(self.labelPedal1Param4, 6, 0, 1, 1)
        self.progressBarPedal1Param2 = ParamProgressBar(self.groupBoxPedal1)
        self.progressBarPedal1Param2.setProperty("value", 24)
        self.progressBarPedal1Param2.setObjectName("progressBarPedal1Param2")
        self.gridLayout_2.addWidget(self.progressBarPedal1Param2, 4, 2, 1, 1)
        self.labelPedal1Param5 = QtWidgets.QLabel(self.groupBoxPedal1)
        self.labelPedal1Param5.setObjectName("labelPedal1Param5")
        self.gridLayout_2.addWidget(self.labelPedal1Param5, 7, 0, 1, 1)
        self.labelPedal1Param2 = QtWidgets.QLabel(self.groupBoxPedal1)
        self.labelPedal1Param2.setObjectName("labelPedal1Param2")
        self.gridLayout_2.addWidget(self.labelPedal1Param2, 4, 0, 1, 1)
        self.labelPedal1Param1 = QtWidgets.QLabel(self.groupBoxPedal1)
        self.labelPedal1Param1.setObjectName("labelPedal1Param1")
        self.gridLayout_2.addWidget(self.labelPedal1Param1, 3, 0, 1, 1)
        self.progressBarPedal1Param0 = ParamProgressBar(self.groupBoxPedal1)
        self.progressBarPedal1Param0.setProperty("value", 24)
        self.progressBarPedal1Param0.setObjectName("progressBarPedal1Param0")
        self.gridLayout_2.addWidget(self.progressBarPedal1Param0, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem4, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBoxPedal1)
        self.groupBoxPedal2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxPedal2.setStyleSheet("QGroupBox {\n"
"    background-color:#20808080;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 1.5ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center; /* position at the top center */\n"
"    padding: 0 3px;\n"
"    border:2px solid gray;\n"
"    border-radius:5px;\n"
"}")
        self.groupBoxPedal2.setCheckable(True)
        self.groupBoxPedal2.setObjectName("groupBoxPedal2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxPedal2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelPedal2Param1 = QtWidgets.QLabel(self.groupBoxPedal2)
        self.labelPedal2Param1.setObjectName("labelPedal2Param1")
        self.gridLayout_3.addWidget(self.labelPedal2Param1, 3, 0, 1, 1)
        self.progressBarPedal2Param4 = ParamProgressBar(self.groupBoxPedal2)
        self.progressBarPedal2Param4.setProperty("value", 24)
        self.progressBarPedal2Param4.setObjectName("progressBarPedal2Param4")
        self.gridLayout_3.addWidget(self.progressBarPedal2Param4, 6, 1, 1, 1)
        self.progressBarPedal2Param5 = ParamProgressBar(self.groupBoxPedal2)
        self.progressBarPedal2Param5.setProperty("value", 24)
        self.progressBarPedal2Param5.setObjectName("progressBarPedal2Param5")
        self.gridLayout_3.addWidget(self.progressBarPedal2Param5, 7, 1, 1, 1)
        self.labelPedal2Param2 = QtWidgets.QLabel(self.groupBoxPedal2)
        self.labelPedal2Param2.setObjectName("labelPedal2Param2")
        self.gridLayout_3.addWidget(self.labelPedal2Param2, 4, 0, 1, 1)
        self.progressBarPedal2Param2 = ParamProgressBar(self.groupBoxPedal2)
        self.progressBarPedal2Param2.setProperty("value", 24)
        self.progressBarPedal2Param2.setObjectName("progressBarPedal2Param2")
        self.gridLayout_3.addWidget(self.progressBarPedal2Param2, 4, 1, 1, 1)
        self.progressBarPedal2Param3 = ParamProgressBar(self.groupBoxPedal2)
        self.progressBarPedal2Param3.setProperty("value", 24)
        self.progressBarPedal2Param3.setObjectName("progressBarPedal2Param3")
        self.gridLayout_3.addWidget(self.progressBarPedal2Param3, 5, 1, 1, 1)
        self.labelPedal2Param5 = QtWidgets.QLabel(self.groupBoxPedal2)
        self.labelPedal2Param5.setObjectName("labelPedal2Param5")
        self.gridLayout_3.addWidget(self.labelPedal2Param5, 7, 0, 1, 1)
        self.labelPedal2Param3 = QtWidgets.QLabel(self.groupBoxPedal2)
        self.labelPedal2Param3.setObjectName("labelPedal2Param3")
        self.gridLayout_3.addWidget(self.labelPedal2Param3, 5, 0, 1, 1)
        self.progressBarPedal2Param1 = ParamProgressBar(self.groupBoxPedal2)
        self.progressBarPedal2Param1.setProperty("value", 24)
        self.progressBarPedal2Param1.setObjectName("progressBarPedal2Param1")
        self.gridLayout_3.addWidget(self.progressBarPedal2Param1, 3, 1, 1, 1)
        self.progressBarPedal2Param0 = ParamProgressBar(self.groupBoxPedal2)
        self.progressBarPedal2Param0.setProperty("value", 24)
        self.progressBarPedal2Param0.setObjectName("progressBarPedal2Param0")
        self.gridLayout_3.addWidget(self.progressBarPedal2Param0, 2, 1, 1, 1)
        self.comboBoxPedal2 = QtWidgets.QComboBox(self.groupBoxPedal2)
        self.comboBoxPedal2.setObjectName("comboBoxPedal2")
        self.gridLayout_3.addWidget(self.comboBoxPedal2, 1, 0, 1, 3)
        self.labelPedal2Param0 = QtWidgets.QLabel(self.groupBoxPedal2)
        self.labelPedal2Param0.setObjectName("labelPedal2Param0")
        self.gridLayout_3.addWidget(self.labelPedal2Param0, 2, 0, 1, 1)
        self.labelPedal2Param4 = QtWidgets.QLabel(self.groupBoxPedal2)
        self.labelPedal2Param4.setObjectName("labelPedal2Param4")
        self.gridLayout_3.addWidget(self.labelPedal2Param4, 6, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem5, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBoxPedal2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 506, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tronix Hammer"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Amp"))
        self.label_7.setText(_translate("MainWindow", "Resonance"))
        self.label_3.setText(_translate("MainWindow", "Middle"))
        self.label_5.setText(_translate("MainWindow", "Volume"))
        self.labelPresenceTone.setText(_translate("MainWindow", "Tone"))
        self.checkBoxLowCut.setText(_translate("MainWindow", "Low Cut"))
        self.checkBoxMidBoost.setText(_translate("MainWindow", "Mid Boost"))
        self.checkBoxBrightCap.setText(_translate("MainWindow", "Bright Cap"))
        self.label_4.setText(_translate("MainWindow", "Bass"))
        self.label_2.setText(_translate("MainWindow", "Treble"))
        self.label.setText(_translate("MainWindow", "Gain"))
        self.checkBoxClassAAB.setText(_translate("MainWindow", "Class A/AB"))
        self.checkBoxBiasShift.setText(_translate("MainWindow", "Bias Shift"))
        self.label_6.setText(_translate("MainWindow", "Noise Gate"))
        self.groupBoxReverb.setTitle(_translate("MainWindow", "Reverb"))
        self.label_20.setText(_translate("MainWindow", "Time"))
        self.label_21.setText(_translate("MainWindow", "Pre Delay"))
        self.label_19.setText(_translate("MainWindow", "Mix"))
        self.label_22.setText(_translate("MainWindow", "Low Damp"))
        self.label_23.setText(_translate("MainWindow", "High Damp"))
        self.groupBoxPedal1.setTitle(_translate("MainWindow", "Pedal 1"))
        self.labelPedal1Param0.setText(_translate("MainWindow", "Param0"))
        self.labelPedal1Param3.setText(_translate("MainWindow", "Param3"))
        self.labelPedal1Param4.setText(_translate("MainWindow", "Param4"))
        self.labelPedal1Param5.setText(_translate("MainWindow", "Param5"))
        self.labelPedal1Param2.setText(_translate("MainWindow", "Param2"))
        self.labelPedal1Param1.setText(_translate("MainWindow", "Param1"))
        self.groupBoxPedal2.setTitle(_translate("MainWindow", "Pedal 2"))
        self.labelPedal2Param1.setText(_translate("MainWindow", "Param1"))
        self.labelPedal2Param2.setText(_translate("MainWindow", "Param2"))
        self.labelPedal2Param5.setText(_translate("MainWindow", "Param5"))
        self.labelPedal2Param3.setText(_translate("MainWindow", "Param3"))
        self.labelPedal2Param0.setText(_translate("MainWindow", "Param0"))
        self.labelPedal2Param4.setText(_translate("MainWindow", "Param4"))
from ui.progress import ParamProgressBar
